theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
mouse = false
end-of-line-diagnostics = "hint"
cursorline = true
color-modes = true

[editor.indent-guides]
render = true


[editor.cursor-shape]
insert = "bar"
normal = "block"


[keys.insert]
j = {k = "normal_mode"}

[editor.inline-diagnostics]
cursor-line = "warning"
