theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
mouse = false
end-of-line-diagnostics = "hint"
cursorline = true
color-modes = true
true-color = true

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 1


[editor.cursor-shape]
insert = "bar"


[keys.insert]
j = {k = "normal_mode"}

[editor.inline-diagnostics]
cursor-line = "warning"
